# .streamlit/config.toml
[theme]
primaryColor="#FF4B4B" # Example: A bright red/pink for accents
backgroundColor="#F0F2F6" # A light, friendly background
secondaryBackgroundColor="#FFFFFF" # For cards/containers
textColor="#262730"
font="sans serif"